config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/rcstar/openQxD:
      branch: master
      repo: https://gitlab.com/rcstar/openQxD
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/rcstar/openQxD git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-carmine-squirt.sh
        container: qc.acc_greasy-aquamarine-nightingale
  QC.Doc:
    repos:
      gitlab.com/rcstar/openQxD find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-wheat-lemur.sh
        container: qc.doc_surly-lemon-kingfisher
      gitlab.com/rcstar/openQxD git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-pumpkin-ragdoll.sh
        container: qc.doc_stuffy-ecru-cheetah
      gitlab.com/rcstar/openQxD markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-pear-cattle.sh
        container: qc.doc_gloppy-lemon-insect
  QC.Lic:
    repos:
      gitlab.com/rcstar/openQxD licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-tangerine-wallaby.sh
        container: qc.lic_leaky-apricot-coral
  QC.Sty:
    repos:
      gitlab.com/rcstar/openQxD oclint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-copper-impala.sh
        container: qc.sty_woozy-rose-chin
  QC.Ver:
    repos:
      gitlab.com/rcstar/openQxD get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-amethyst-cichlid.sh
        container: qc.ver_homey-peach-squid
timeout: 5400
